### What are Tensors ?
Tensors is a specialized multi-dimensional array designed for mathematical and computational efficiency.

***Tensors can be in any dimensions :***
1. Scalar => 0-dimensional tensors(a single number)

    - Ex: 5.0 , -3.14...etc
2. Vectors => 1-dimensional tensors(a list of numbers)

    - Ex: [0.12,3.1,21.34,21.45]
3. Matrices => 2-dimensional tensors(a 2D grid of numbers)

    - Ex : [[1.2,3.0,244]
         [8.0,2.1,3.4]]

4. 3D tensors (Coloured image)

    - Ex : RGB image (256,256,3) -> Here 256x256 represents a 2d tensors which is in 3 dimensions(3 colors i,e. R,G,B)

5. 4D tensors (Batches of RGB images = video)

    - Ex : (32,128,128,3) A batch of 32 images, each of size 128x128 with 3 colour channels(RGB)

6. 5D tensors (Video data = Group of videos)

    - Ex : (10,16,64,64,3) A batch of 10 video clips, each with 16 frames of size 64x64 and 3 channels (RGB)

#### Why are Tensors Useful ?

***1. Mathematical Operations :***

Tensors enable efficient mathematical computations necessary for neural network operations.

***2. Representation of Real-world Data :***

Data like images, audio, Video and Text can be easily represented as tensors.

***3. Efficient Computations :***

Tensors are optimized for hardware acceleration , allowing parallel computations on GPUs or TPUs, which are crucial for training deep learning models   

### Practical

In [1]:
# Importing Pytorch
import torch
print(torch.__version__)

2.10.0+cpu


#### Creating Tensors

In [2]:
# 1. Empty Tensor -> It assign the memory for the tensor by assigning some randome values
emp_tensor = torch.empty(2,3)
print(emp_tensor)

tensor([[3.0790e-18, 3.1360e+27, 7.0800e+31],
        [3.1095e-18, 4.7851e+22, 2.8826e+32]])


In [3]:
# 2. Zeros Tensors
zero_tr = torch.zeros(4,3)
print(zero_tr)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# 3. Ones Tensors
ones_tr = torch.ones(2,3)
print(ones_tr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# 4. Random Values tensors -> Create a tensors with random value
rand_tr = torch.rand(2,3)
print(rand_tr)

tensor([[0.1795, 0.1119, 0.1079],
        [0.2839, 0.1398, 0.7000]])


In [6]:
# 5. Custom value tensors
my_tensors = torch.tensor([[0.6011, 0.7549, 0.4365],
        [0.7124, 0.5328, 0.3945]])
print(my_tensors)

tensor([[0.6011, 0.7549, 0.4365],
        [0.7124, 0.5328, 0.3945]])


In [7]:
# 6 . Range of values in tensors
arange_tr = torch.arange(2,20,2) # start,stop,step
print(arange_tr)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])


In [8]:
# 7. linearly spaced tensors
linSpace_tr = torch.linspace(0,10,8) # start,stop,total values
print(linSpace_tr)

tensor([ 0.0000,  1.4286,  2.8571,  4.2857,  5.7143,  7.1429,  8.5714, 10.0000])


In [9]:
# 8. Eye tensor (a Identity matrix tensor)
eye_tr = torch.eye(5)
print(eye_tr)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [10]:
# 9. full matrix (a tensor consist of a single value)
full_tr = torch.full((2,3),7)
print(full_tr)

tensor([[7, 7, 7],
        [7, 7, 7]])


#### Tensor Shapes

In [11]:
my_tr = torch.tensor([[1,2,5],[3,4,6]])
print(my_tr)

tensor([[1, 2, 5],
        [3, 4, 6]])


In [12]:
print("Shape of a tensor : ",my_tr.shape)

Shape of a tensor :  torch.Size([2, 3])


In [13]:
# Creating an empty tensor with the same shape of a tensor we have , with random values

alike_tr = torch.empty_like(my_tr)
print("Same shape tensor : ",alike_tr)

Same shape tensor :  tensor([[3616445622929465956, 6066684243246853430, 3977305399563531313],
        [6499591696621320238, 7309453675965983778, 8315168162784306286]])


In [14]:
# Creating an empty tensor with the same shape of a tensor we have, with zeros values
zero_alike_tr = torch.zeros_like(my_tr)
print("Same shape tesnsor with zeros : ",zero_alike_tr)

Same shape tesnsor with zeros :  tensor([[0, 0, 0],
        [0, 0, 0]])


In [15]:
# Creating an empty tensor with the same shape of a tensor we have, with ones values
ones_alike_tr = torch.ones_like(my_tr)
print("Same shape tesnsor with ones : ",ones_alike_tr)

Same shape tesnsor with ones :  tensor([[1, 1, 1],
        [1, 1, 1]])


#### Tensor Data Types

In [16]:
#find data type of a tensor
my_tr.dtype

torch.int64

In [17]:
#creating a tensor with custom datatype
float_tr = torch.tensor([[1,2],[4,5]],dtype=torch.float32)
print(float_tr)

tensor([[1., 2.],
        [4., 5.]])


In [18]:
# Converting an existing tensor from one datatype to another
converted_tr = my_tr.to(dtype=torch.float64)
print(converted_tr)

tensor([[1., 2., 5.],
        [3., 4., 6.]], dtype=torch.float64)


#### Mathematical Operations

##### 1. Scalar Operation

In [19]:
my_tr = torch.tensor([[1,2],[3,4]])

In [20]:
# Addition
my_tr + 2

tensor([[3, 4],
        [5, 6]])

In [21]:
# Substraction
my_tr - 1

tensor([[0, 1],
        [2, 3]])

In [22]:
# Multiplication
my_tr * 3

tensor([[ 3,  6],
        [ 9, 12]])

In [23]:
# Division
my_tr / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [24]:
# Floor Division
my_tr // 2

tensor([[0, 1],
        [1, 2]])

In [25]:
# Modulus Operation
my_tr % 3

tensor([[1, 2],
        [0, 1]])

In [26]:
# Power
my_tr ** 2

tensor([[ 1,  4],
        [ 9, 16]])

##### 2. Element wise tensor operations

In [27]:
tr_a = torch.tensor([[1,2],[3,4]])
tr_b = torch.tensor([[5,6],[7,8]])
print(tr_a)
print(tr_b)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [28]:
# Addition
tr_a + tr_b

tensor([[ 6,  8],
        [10, 12]])

In [29]:
# Substraction
tr_a - tr_b

tensor([[-4, -4],
        [-4, -4]])

In [30]:
# Multiplication
tr_a * tr_b

tensor([[ 5, 12],
        [21, 32]])

In [31]:
# Division
tr_a / tr_b

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [32]:
# Floor Division
tr_a // tr_b

tensor([[0, 0],
        [0, 0]])

In [33]:
# Modulus Operation
tr_a % tr_b

tensor([[1, 2],
        [3, 4]])

In [34]:
# Power
tr_a ** tr_b

tensor([[    1,    64],
        [ 2187, 65536]])

In [35]:
tr_c = torch.tensor([[12.2,-29.4],[21.3,34.8]])

In [36]:
# Asolute values
torch.abs(tr_c)

tensor([[12.2000, 29.4000],
        [21.3000, 34.8000]])

In [37]:
# Converting nums to negative
torch.neg(tr_c)

tensor([[-12.2000,  29.4000],
        [-21.3000, -34.8000]])

In [38]:
# round of operation
torch.round(tr_c)

tensor([[ 12., -29.],
        [ 21.,  35.]])

In [39]:
# ceil operation
torch.ceil(tr_c)

tensor([[ 13., -29.],
        [ 22.,  35.]])

In [40]:
# Floor operation
torch.floor(tr_c)

tensor([[ 12., -30.],
        [ 21.,  34.]])

##### 3. Reduction Operations

In [41]:
tr_d = torch.tensor([[1,2,3],[4,5,6]])

In [42]:
# Sum of all elems in a tensor
torch.sum(tr_d)

tensor(21)

In [43]:
# Sum along columns
torch.sum(tr_d,dim=0)

tensor([5, 7, 9])

In [44]:
# Sum along rows
torch.sum(tr_d,dim=1)

tensor([ 6, 15])

In [45]:
# Mean of the entire tensor
tr_d = tr_d.to(dtype=torch.float32)
torch.mean(tr_d)

tensor(3.5000)

In [46]:
# Mean along columns
torch.mean(tr_d,dim=0)

tensor([2.5000, 3.5000, 4.5000])

In [47]:
# Mean along rows
torch.mean(tr_d,dim=1)

tensor([2., 5.])

In [48]:
# Median of the entire tensor
torch.median(tr_d)

tensor(3.)

In [49]:
# Median along columns
torch.median(tr_d,dim=0)

torch.return_types.median(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

In [50]:
# Median along rows
torch.median(tr_d,dim=1)

torch.return_types.median(
values=tensor([2., 5.]),
indices=tensor([1, 1]))

In [51]:
# Max value in a tensor
torch.max(tr_d)

tensor(6.)

In [52]:
# Min value in a tensor
torch.min(tr_d)

tensor(1.)

In [53]:
# Product of all elems in tensor
torch.prod(tr_d)

tensor(720.)

In [54]:
# Standard deviation of a tensor
torch.std(tr_d)

tensor(1.8708)

In [55]:
# Variance
torch.var(tr_d)

tensor(3.5000)

In [56]:
# argmax -> position of the max elem
torch.argmax(tr_d)

tensor(5)

In [57]:
# argmin -> position of the min elem
torch.argmin(tr_d)

tensor(0)

##### 4. Matrix Operations

In [58]:
tr_e = torch.randint(size=(3,3),low=0,high=10)
tr_f = torch.randint(size=(3,2),low=0,high=10)
print(tr_e)
print(tr_f)

tensor([[8, 2, 7],
        [6, 8, 2],
        [0, 7, 2]])
tensor([[8, 0],
        [9, 3],
        [2, 5]])


In [59]:
#  Matrix Multiplication
torch.matmul(tr_e,tr_f)

tensor([[ 96,  41],
        [124,  34],
        [ 67,  31]])

In [60]:
# Dot Product
vec1 = torch.tensor([1,2,3])
vec2 = torch.tensor([4,5,6])
torch.dot(vec1,vec2)

tensor(32)

In [61]:
# Transpose of a matrix
torch.transpose(tr_f,0,1)

tensor([[8, 9, 2],
        [0, 3, 5]])

In [62]:
# Determinant of a matrix
tr_e = tr_e.to(dtype=torch.float64)
torch.det(tr_e)

tensor(286., dtype=torch.float64)

In [63]:
# Inverse of a matrix
torch.inverse(tr_e)

tensor([[ 0.0070,  0.1573, -0.1818],
        [-0.0420,  0.0559,  0.0909],
        [ 0.1469, -0.1958,  0.1818]], dtype=torch.float64)

##### 5. Comparison Operations

In [64]:
tr_g = torch.randint(size=(2,2),low=0,high=10)
tr_h = torch.randint(size=(2,2),low=0,high=10)
print(tr_g)
print(tr_h)

tensor([[0, 1],
        [0, 4]])
tensor([[4, 4],
        [8, 2]])


In [65]:
# Greater than
tr_g > tr_h

tensor([[False, False],
        [False,  True]])

In [66]:
# Less than
tr_g < tr_h

tensor([[ True,  True],
        [ True, False]])

In [67]:
# equals
tr_g == tr_h

tensor([[False, False],
        [False, False]])

In [68]:
# less than equals
tr_g <= tr_h

tensor([[ True,  True],
        [ True, False]])

In [69]:
# greater than equals
tr_g >= tr_h

tensor([[False, False],
        [False,  True]])

In [70]:
# not equal to
tr_g != tr_h

tensor([[True, True],
        [True, True]])

##### 6. Special Functions

In [71]:
tr_i = torch.randint(size=(2,3),low=0,high=10)
print(tr_i)

tensor([[3, 8, 1],
        [9, 9, 0]])


In [72]:
# Log value
torch.log(tr_i)

tensor([[1.0986, 2.0794, 0.0000],
        [2.1972, 2.1972,   -inf]])

In [73]:
# exponents value
torch.exp(tr_i)

tensor([[2.0086e+01, 2.9810e+03, 2.7183e+00],
        [8.1031e+03, 8.1031e+03, 1.0000e+00]])

In [74]:
#square root value
torch.sqrt(tr_i)

tensor([[1.7321, 2.8284, 1.0000],
        [3.0000, 3.0000, 0.0000]])

In [75]:
# sigmoid
torch.sigmoid(tr_i)

tensor([[0.9526, 0.9997, 0.7311],
        [0.9999, 0.9999, 0.5000]])

In [76]:
# Softmax
tr_i = tr_i.to(dtype=torch.float32)
torch.softmax(tr_i,dim=0)

tensor([[0.0025, 0.2689, 0.7311],
        [0.9975, 0.7311, 0.2689]])

#### In-Place Operations

To do the in-place operations on the tensors we have to just append the underscore "_" at the end of the operation we have to perform.

Ex : x.add_(y), x.relu_(y)

In [77]:
tr_j = torch.randint(size=(2,3),low=0,high=10)
tr_k = torch.randint(size=(2,3),low=0,high=10)
print(tr_j)
print(tr_k)

tensor([[1, 8, 8],
        [6, 7, 9]])
tensor([[6, 6, 7],
        [5, 9, 0]])


In [78]:
# Addition In-place operation
tr_j.add_(tr_k) # Here change will be applicable to original tr_j tensor

tensor([[ 7, 14, 15],
        [11, 16,  9]])

In [80]:
tr_j

tensor([[ 7, 14, 15],
        [11, 16,  9]])

#### Copying a Tensor

In [82]:
tr_j

tensor([[ 7, 14, 15],
        [11, 16,  9]])

In [84]:
tr_j_copy = tr_j.clone()
print(tr_j_copy)

tensor([[ 7, 14, 15],
        [11, 16,  9]])


In [86]:
tr_j[0][0] = 9

print(tr_j)

tensor([[ 9, 14, 15],
        [11, 16,  9]])


In [87]:
tr_j_copy # As we can see here there is no change in the copy of the tensor

tensor([[ 7, 14, 15],
        [11, 16,  9]])

In [88]:
id(tr_j)

134927708264944

In [89]:
id(tr_j_copy)

134927707982576

#### Reshaping Tensors

In [7]:
tr_k = torch.randint(size=(2,3),low=0,high=15)
tr_k

tensor([[ 9,  9,  5],
        [13,  4, 13]])

In [8]:
tr_k.shape

torch.Size([2, 3])

In [15]:
# Reshaping a tensor
tr_k = tr_k.reshape((3,2)) # 3- no_of_row, 2- no_of_column

In [16]:
tr_k

tensor([[ 9,  9],
        [ 5, 13],
        [ 4, 13]])

In [17]:
# Flatten a tensor
tr_k.flatten()

tensor([ 9,  9,  5, 13,  4, 13])

In [26]:
tr_l = torch.rand(2,3,4)
print("Before Permute ",tr_l.shape)

# Permute operation : we can rearrange the dimesnions of the tensor with permute
tr_l = tr_l.permute(2,0,1) # Here 2,0,1 : Indices => (2,3,4): dimensions means the position of the dimensions is rearranged i,e 2 is replace with 4 dimension, 3 with 2 and 4 with 3 dimesnions
# So now shape will transform from (2,3,4) to (4,2,3)
print("After permute : ",tr_l.shape)

Before Permute  torch.Size([2, 3, 4])
After permute :  torch.Size([4, 2, 3])


#### Tensor Operation on GPU

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = torch.device("cuda")

In [4]:
device

device(type='cuda')

In [5]:
# This only works if we are working in GPU environment
tr_gpu = torch.randint(size=(2,2),low=0,high=10,device=device)
tr_gpu

tensor([[5, 6],
        [0, 0]], device='cuda:0')

In [6]:
# Transfering a normal cpu tensor to GPU
tr_cpu_a = torch.randint(size=(2,2),low=0,high=10) # CPU Tensors
tr_gpu_a = tr_cpu_a.to(device=device)
tr_gpu_a

tensor([[8, 9],
        [9, 1]], device='cuda:0')

#### Numpy and PyTorch

We convert numpy array to PyTorch tensor and vice versa...

In [27]:
import numpy as np
import torch

Converting from numpy array to PyTorch tensor

In [28]:
np_arr = np.array([1,2,3])
np_arr

array([1, 2, 3])

In [29]:
type(np_arr)

numpy.ndarray

In [30]:
#
con_tr = torch.from_numpy(np_arr)
con_tr

tensor([1, 2, 3])

In [31]:
type(con_tr)

torch.Tensor

Converting from PyTorch tensor to Numpy Array

In [32]:
tr_tensor = torch.tensor([4,5,6])
tr_tensor

tensor([4, 5, 6])

In [33]:
type(tr_tensor)

torch.Tensor

In [34]:
con_np_arr = tr_tensor.numpy()
con_np_arr

array([4, 5, 6])

In [35]:
type(con_np_arr)

numpy.ndarray