## Creating a simple neural network using Pytorch
By creating a Proper PyTorch Training Pipeline

#### **Flow  of the Training**
1. Load the Dataset
2. Data PreProcessing
3. Training Process
    1. Create the model
    2. Forward Propogation
    3. Loss Calculation
    4. Back Propogation
    5. Parameters Updation
4. Model Evaluation

In [ ]:
# Imports
import torch
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler , LabelEncoder # For Scaling
from sklearn.model_selection import train_test_split

#### 1. Load Dataset

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
df.shape

(569, 33)

#### 2. Data Preprocessing

In [ ]:
# Removing unnecessary columns
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [ ]:
df.shape

(569, 31)

##### Train Test Split

In [58]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=1)

print("X_train : ",X_train.shape)
print("X_test : ",X_test.shape)
print("y_train : ",y_train.shape)
print("y_test : ",y_test.shape)

X_train :  (455, 30)
X_test :  (114, 30)
y_train :  (455,)
y_test :  (114,)


##### Scaling

In [59]:
#  Here our data is in different scaling( or range) so to normalize or scale it to a same scale , we will do the scaling on the features input using StandardScaler
print("Before Scaling")
print("X_train",X_train)
print("X_test",X_test)

Before Scaling
X_train      radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
408        17.99         20.66          117.80      991.7          0.10360   
4          20.29         14.34          135.10     1297.0          0.10030   
307         9.00         14.40           56.36      246.3          0.07005   
386        12.21         14.09           78.78      462.0          0.08108   
404        12.34         14.95           78.29      469.1          0.08682   
..           ...           ...             ...        ...              ...   
129        19.79         25.12          130.40     1192.0          0.10150   
144        10.75         14.97           68.26      355.3          0.07793   
72         17.20         24.52          114.20      929.4          0.10710   
235        14.03         21.25           89.79      603.4          0.09070   
37         13.03         18.42           82.61      523.8          0.08983   

     compactness_mean  concavity_mean  c

In [60]:

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [61]:
X_train

array([[ 1.0449852 ,  0.29708512,  1.01044815, ...,  1.21839781,
         0.29811854,  0.08380738],
       [ 1.68141074, -1.14098169,  1.70338066, ...,  0.69716372,
        -0.88595033, -0.41234747],
       [-1.44260855, -1.12732916, -1.4504636 , ..., -1.52233766,
         0.1807324 , -0.33657109],
       ...,
       [ 0.82638686,  1.17539807,  0.86625411, ...,  1.10638475,
         0.72853438,  3.02284824],
       [-0.05077356,  0.43133503, -0.11146165, ..., -0.54050588,
        -1.1207226 , -0.44903285],
       [-0.32748032, -0.21260945, -0.39904866, ..., -0.98109057,
        -1.52732096, -1.31985978]])

In [62]:
X_test

array([[ 2.92635643e-01, -1.30427498e+00,  4.09740749e-01, ...,
         1.73162033e-02, -1.90246784e-01,  3.02591603e-01],
       [-1.97911946e-01, -9.58755925e-02, -1.69337819e-01, ...,
         1.64947589e+00,  1.29351802e+00,  1.43498453e+00],
       [-2.68912255e-01, -7.77536786e-01, -3.03699185e-01, ...,
        -6.92881882e-02,  5.74452130e-01,  4.67494678e-01],
       ...,
       [-1.53433140e+00, -4.39288239e-01, -1.45570598e+00, ...,
         1.08654734e+00,  1.74708265e+00,  1.41744165e+00],
       [ 2.40999055e-01,  7.97038058e-02,  2.21918697e-01, ...,
        -2.30172500e-01, -6.82530353e-01, -4.62716551e-01],
       [-1.04745272e-03, -8.36923935e-01, -5.62661049e-02, ...,
        -1.27642017e+00, -1.52881559e+00, -7.49104072e-01]])

In [63]:
#  Similarly our target labels are categories we will convert it into a numerical label(a binary label as our output labels are only 2 here) because our neural network won't be able to understand this categorical labels

print("Before Label Encoding")
print("y_train")
print(y_train)

Before Label Encoding
y_train
408    M
4      M
307    B
386    B
404    B
      ..
129    M
144    B
72     M
235    B
37     B
Name: diagnosis, Length: 455, dtype: object


In [64]:
print("y_test")
print(y_test)

y_test
421    B
47     M
292    B
186    M
414    M
      ..
172    M
3      M
68     B
448    B
442    B
Name: diagnosis, Length: 114, dtype: object


In [65]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [66]:
y_train

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

In [67]:
y_test

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0])

##### Converting this numpy arrays into PyTorch Tensors

In [68]:
# Before Converting its types
print("X_train : ",type(X_train))
print("X_test : ",type(X_test))

print("y_train : ",type(y_train))
print("y_test : ",type(y_test))


X_train :  <class 'numpy.ndarray'>
X_test :  <class 'numpy.ndarray'>
y_train :  <class 'numpy.ndarray'>
y_test :  <class 'numpy.ndarray'>


In [69]:
X_train_tr = torch.from_numpy(X_train)
X_test_tr = torch.from_numpy(X_test)
y_train_tr = torch.from_numpy(y_train)
y_test_tr = torch.from_numpy(y_test)

In [71]:
# After Converting its types
print("X_train : ",type(X_train_tr))
print("X_test : ",type(X_test_tr))

print("y_train : ",type(y_train_tr))
print("y_test : ",type(y_test_tr))


X_train :  <class 'torch.Tensor'>
X_test :  <class 'torch.Tensor'>
y_train :  <class 'torch.Tensor'>
y_test :  <class 'torch.Tensor'>


#### 3. Model Training Process

***Important Parameters***

In [127]:
learning_rate = 0.1
epochs = 50 # Training loop count

In [128]:
X_train.shape

(455, 30)

##### 1. Defining Model

In [129]:
class MySimpleNN:
  def __init__(self,X_train):
    # Defining random weights of shape (30,1) ; Here 30 is the num of input features
    self.weights = torch.rand(size=(X_train.shape[1],1),dtype=torch.float64,requires_grad=True)
    # Defining bias
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  # 2. Forward Propogation
  def forward_prop(self,X_train):
    """
      Formula :
        z = weights * X + bias
        ypred = sigmoid(z)
    """
    z = torch.matmul(X_train,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  # 3. Loss Calculation
  def loss_calculation(self,y_pred,y_train):
    """
      Binary cross entropy loss function
      Formula :
        L =  -[y_train * ln(y_pred) + (1-y_train) * ln(1 - y_pred)]
    """

    epsilon = 1e-7
    # Clipping or clamping y_pred values
    y_pred = torch.clamp(y_pred,min=epsilon,max=1 - epsilon)

    loss = - (y_train * torch.log(y_pred) + (1-y_train) * torch.log(1-y_pred)).mean()

    return loss

In [130]:
##### 1. Defining the model
model = MySimpleNN(X_train_tr)

##### Training Process for the num of epochs

In [131]:
for epoch in range(epochs):

  ##### 2. Forward Propogation
  y_pred = model.forward_prop(X_train_tr)

  ##### 3. Loss Calculation
  loss = model.loss_calculation(y_pred,y_train_tr)
  # print("Loss : ",loss)

  ##### 4. Backward Propogation
  loss.backward() # Using Autograd

  ##### 5. Parameters Updates
  """
    Formula to update parameters:
      Wnew = Wold - learning_rate * (dL/dW)
      Bnew = Bold - learning_rate * (dL/dB)
  """

  # Not caluculatin gradient for the updated weights and bias
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Cleaning gradients so that it should accumulate for the next run
  model.weights.grad.zero_()
  model.bias.grad.zero_()


  print(f"Epoch : {epoch + 1} , Loss : {loss:.4f}")

Epoch : 1 , Loss : 3.8969
Epoch : 2 , Loss : 3.7800
Epoch : 3 , Loss : 3.6606
Epoch : 4 , Loss : 3.5385
Epoch : 5 , Loss : 3.4113
Epoch : 6 , Loss : 3.2737
Epoch : 7 , Loss : 3.1334
Epoch : 8 , Loss : 2.9834
Epoch : 9 , Loss : 2.8280
Epoch : 10 , Loss : 2.6656
Epoch : 11 , Loss : 2.5032
Epoch : 12 , Loss : 2.3371
Epoch : 13 , Loss : 2.1705
Epoch : 14 , Loss : 2.0063
Epoch : 15 , Loss : 1.8471
Epoch : 16 , Loss : 1.6925
Epoch : 17 , Loss : 1.5464
Epoch : 18 , Loss : 1.4141
Epoch : 19 , Loss : 1.2974
Epoch : 20 , Loss : 1.1952
Epoch : 21 , Loss : 1.1058
Epoch : 22 , Loss : 1.0341
Epoch : 23 , Loss : 0.9786
Epoch : 24 , Loss : 0.9367
Epoch : 25 , Loss : 0.9056
Epoch : 26 , Loss : 0.8823
Epoch : 27 , Loss : 0.8647
Epoch : 28 , Loss : 0.8508
Epoch : 29 , Loss : 0.8395
Epoch : 30 , Loss : 0.8300
Epoch : 31 , Loss : 0.8217
Epoch : 32 , Loss : 0.8143
Epoch : 33 , Loss : 0.8075
Epoch : 34 , Loss : 0.8013
Epoch : 35 , Loss : 0.7956
Epoch : 36 , Loss : 0.7903
Epoch : 37 , Loss : 0.7853
Epoch : 38

In [132]:
model.weights

tensor([[-0.1567],
        [ 0.1054],
        [-0.0839],
        [ 0.2888],
        [-0.0770],
        [-0.2294],
        [-0.2960],
        [-0.4912],
        [-0.2852],
        [ 0.2945],
        [ 0.2359],
        [-0.2234],
        [-0.1878],
        [ 0.3935],
        [-0.0878],
        [ 0.2115],
        [-0.3761],
        [ 0.0393],
        [ 0.5594],
        [ 0.1976],
        [ 0.3097],
        [ 0.0530],
        [ 0.0184],
        [ 0.2835],
        [ 0.2819],
        [ 0.0006],
        [-0.1551],
        [ 0.0101],
        [-0.1114],
        [ 0.2679]], dtype=torch.float64, requires_grad=True)

In [133]:
model.bias

tensor([-0.2713], dtype=torch.float64, requires_grad=True)

#### 4. Model Evaluation

In [139]:
with torch.no_grad():
  y_pred = model.forward_prop(X_test_tr)

  # As we are getting the y_pred in the range of 0 to 1, but we want binary 0 or 1 so we are normalizing it
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tr).float().mean()

print(f"Accuracy : {accuracy.item():.4f}")

Accuracy : 0.5462
